services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb,s3
      - DEBUG=0
      - LS_LOG=warn
      - DATA_DIR=/var/lib/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
    networks:
      - net

networks:
  net:
    driver: bridge
