variable "bucket_name" {
  description = "Globally unique S3 bucket name — generated by bootstrap.sh"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "dynamo_rag_table_name" {
  description = "DynamoDB table for RAG embeddings"
  type        = string
  default     = "BotFactoryRAG"
}

variable "dynamo_history_table_name" {
  description = "DynamoDB table for conversation history"
  type        = string
  default     = "BotFactoryHistory"
}

variable "dynamo_logs_table_name" {
  description = "DynamoDB table for chat logs"
  type        = string
  default     = "BotFactoryLogs"
}

variable "dynamo_api_keys_table_name" {
  description = "DynamoDB table for API keys"
  type        = string
  default     = "BotFactoryApiKeys"
}

variable "dynamo_rate_limit_table_name" {
  description = "DynamoDB table for per-key/per-IP rate limit counters"
  type        = string
  default     = "BotFactoryRateLimit"
}

variable "budget_notification_email" {
  description = "Email address for Bedrock budget alarm notifications"
  type        = string
}

variable "bedrock_monthly_budget_usd" {
  description = "Monthly Bedrock spend cap (USD) before the 80%/100% alarms fire"
  type        = number
  default     = 20
}
