variable "bucket_name" {
  description = "Globally unique S3 bucket name — generated by bootstrap.sh"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "dynamo_table_name" {
  description = "DynamoDB table for RAG embeddings"
  type        = string
  default     = "BotFactoryRAG"
}

variable "dynamo_logs_table_name" {
  description = "DynamoDB table for chat logs"
  type        = string
  default     = "BotFactoryLogs"
}
